// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMnA9LswiJSFTFcGVFYg4vfXaCu_8PQw',
    appId: '1:890408466873:web:409d044a152dfa1dff5e68',
    messagingSenderId: '890408466873',
    projectId: 'safenest-dec7d',
    authDomain: 'safenest-dec7d.firebaseapp.com',
    storageBucket: 'safenest-dec7d.firebasestorage.app',
    measurementId: 'G-LK9D5ZT6CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPu7i3u6cxFBQwspEnUgL27_-MIEQfu9s',
    appId: '1:890408466873:android:479a76e45f8a4174ff5e68',
    messagingSenderId: '890408466873',
    projectId: 'safenest-dec7d',
    storageBucket: 'safenest-dec7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCOdp3CU2_fLEuHb8YfRmk-5BDWYwYvMg',
    appId: '1:890408466873:ios:526c8ba2d2b5c8c7ff5e68',
    messagingSenderId: '890408466873',
    projectId: 'safenest-dec7d',
    storageBucket: 'safenest-dec7d.firebasestorage.app',
    iosBundleId: 'com.example.safenest',
  );
}
